// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0aba931f-616e-4088-b235-f3441b152707",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oFYryUXh1",
    "aws_user_pools_web_client_id": "3906bg05dh9tl5pj4aio251v5d",
    "aws_appsync_graphqlEndpoint": "https://u6y7gwpo5vh3ves2e574cfahfe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
